name: Check for new bugs

on:
  schedule:
  - cron: "0 0 1 * *"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5.0.0
      with:
        python-version: 3.8

    - name: Install Requirements
      uses: py-actions/py-dependency-install@v4
      with:
        path: Docker/requirements.txt
        
    - name: Run Script
      run: |
        current_date=$(date -u "+%Y-%m-%d")
        previous_date=$(date -u -d "$current_date" -d "last month" "+%Y-%m-%d")
        python collect_raw_data.py -t ${{ secrets.GITHUB_TOKEN }} -f data/existing_repos.json -d $previous_date -e

    - name: Compare Output, Create Github issue
      run: |
        body=$(python iterate_report.py)
        gh issue create -t "Output of Github Action" -b "$body"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPO: ${{ github.repository }}

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: report
        path: collected/report.json
